Rlpnc 7501 record similarity left and right objects: correct deserialization
rosette-api/java pull request #230
Opened 2024-04-15 06:55 UTC by nnagyprecognoxcom

2024-04-16 19:33 UTC, iredpath requested changes
Other items based on files not included in the current changes (since we're already here fixing a bug):
- `score` in `RecordSimilarityResult` needs to be a `Double`, not a `double`
- `RecordSimilarityExplainInfo` should be annotated with `@JsonInclude(JsonInclude.Include.NON_NULL)`
- We're in this position in the first place because the original code wasn't tested.  Please add a unit test!  I'll attach the one I created while simultaneously working through this issue to the JIRA ticket (I forgot that your team was already handling this fix)

This should not replace any code review/verification by someone on the Nomina team

2024-04-16 19:33 UTC, iredpath commented on json/src/main/java/com/basistech/rosette/apimodel/jackson/recordsimilaritydeserializers/RecordSimilarityDeserializerUtilities.java
> +        return RecordSimilarityResult.builder()
while we're in here already, please fix the related bug where `error` is not being parsed, i.e.
`final String error = node.get("error") != null ? node.get("error").traverse(jsonParser.getCodec()).readValueAs(String.class) : null;` or `String error = Optional.ofNullable(node.get("error")).map(JsonNode::asText).orElse(null);`

2024-04-16 19:33 UTC, iredpath commented on json/src/main/java/com/basistech/rosette/apimodel/jackson/recordsimilaritydeserializers/RecordSimilarityResponseDeserializer.java
> +        JsonNode resultsNode = node.get("results");
this can produce null, so either check that below or default this to an empty node

2024-04-17 13:06 UTC, iredpath approved these changes
LGTM, one or two tiny nitpicks that are going to be addressed in future bindings updates this quarter so no need to get into them now

2024-04-18 12:07 UTC, asoosprecognox commented
I'd like to see the sonar results, but jenkins is failing with a nexus issue currently. Otherwise LGTM

2024-04-18 17:23 UTC, iredpath commented
sonar results - https://sonar.basistech.net/dashboard?id=com.basistech.rosette%3Arosette-api-java-binding&pullRequest=230

2024-04-19 07:21 UTC, asoosprecognox approved these changes

2024-04-19 08:49 UTC, asoosprecognox requested changes
Please fix the Critical and major sonar code smells

2024-04-19 13:45 UTC, nnagyprecognoxcom commented
Sonar smells fixed

2024-04-19 14:26 UTC, asoosprecognox approved these changes

2024-04-19 14:36 UTC, merged